
<?php

session_start();


/* =========================================
   CHECK LOGIN
   ========================================= */

if (
    !isset($_SESSION["user_id"]) ||
    !isset($_SESSION["role"])
)
{
    header("Location: ../avocado_login.php");
    exit();
}


/* =========================================
   ROLE ACCESS
   ========================================= */

$allowed_roles = array(
    "System Administrator",
    "Doctor",
    "Nurse",
    "Reception"
);


if (!in_array($_SESSION["role"], $allowed_roles))
{
    die("Access denied.");
}


/* =========================================
   DATABASE CONNECTION
   ========================================= */

include("../database/peach_database.php");


/* =========================================
   DOMPDF
   ========================================= */

require_once("../vendor/autoload.php");

use Dompdf\Dompdf;
use Dompdf\Options;


/* =========================================
   GET APPOINTMENT RECORDS
   ========================================= */

$result = mysqli_query(
    $connection,
    "SELECT
        appointment.appointment_id,
        patient.patient_name,
        doctor.doctor_name,
        appointment.appointment_date,
        appointment.appointment_time

     FROM appointment

     INNER JOIN patient
     ON appointment.patient_id = patient.patient_id

     INNER JOIN doctor
     ON appointment.doctor_id = doctor.doctor_id

     ORDER BY appointment.appointment_date DESC,
              appointment.appointment_time DESC"
);


if (!$result)
{
    die(
        "Unable to retrieve appointment records: "
        . mysqli_error($connection)
    );
}


/* =========================================
   CREATE HTML
   ========================================= */

$html = '

<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<style>

body
{
    font-family: DejaVu Sans, sans-serif;
    font-size: 10px;
}

h1
{
    text-align:center;
    margin-bottom:5px;
}

.subtitle
{
    text-align:center;
    margin-bottom:20px;
    color:#555;
}

table
{
    width:100%;
    border-collapse:collapse;
}

th
{
    background:#eeeeee;
    border:1px solid #999;
    padding:8px;
    text-align:left;
}

td
{
    border:1px solid #cccccc;
    padding:7px;
}

.footer
{
    margin-top:20px;
    text-align:center;
    font-size:9px;
    color:#666;
}

</style>

</head>

<body>

<h1>CAREFLOW</h1>

<div class="subtitle">

Hospital Management System<br>

Appointment Report

</div>

<table>

<thead>

<tr>

<th>Appointment ID</th>

<th>Patient</th>

<th>Doctor</th>

<th>Date</th>

<th>Time</th>

</tr>

</thead>

<tbody>

';


/* =========================================
   ADD APPOINTMENT DATA
   ========================================= */

while ($row = mysqli_fetch_assoc($result))
{

    $html .= '

    <tr>

    <td>' .
    htmlspecialchars($row["appointment_id"]) .
    '</td>

    <td>' .
    htmlspecialchars($row["patient_name"]) .
    '</td>

    <td>' .
    htmlspecialchars($row["doctor_name"]) .
    '</td>

    <td>' .
    htmlspecialchars($row["appointment_date"]) .
    '</td>

    <td>' .
    htmlspecialchars($row["appointment_time"]) .
    '</td>

    </tr>

    ';

}


$html .= '

</tbody>

</table>

<div class="footer">

Generated by CAREFLOW Hospital Management System

</div>

</body>

</html>

';


/* =========================================
   CREATE PDF
   ========================================= */

$options = new Options();

$options->set(
    "isRemoteEnabled",
    true
);


$dompdf = new Dompdf($options);


$dompdf->loadHtml($html);


$dompdf->setPaper(
    "A4",
    "landscape"
);


$dompdf->render();


/* =========================================
   DOWNLOAD PDF
   ========================================= */

$dompdf->stream(
    "appointment_list.pdf",
    array(
        "Attachment" => true
    )
);

exit();

?>

