
<?php

session_start();


/* =========================================
   CHECK LOGIN
   ========================================= */

if (
    !isset($_SESSION["user_id"]) ||
    !isset($_SESSION["role"])
)
{
    header("Location: ../avocado_login.php");
    exit();
}


/* =========================================
   ROLE ACCESS
   ========================================= */

$allowed_roles = array(
    "System Administrator",
    "Doctor",
    "Nurse",
    "Reception"
);


if (!in_array($_SESSION["role"], $allowed_roles))
{
    die("Access denied.");
}


/* =========================================
   DATABASE CONNECTION
   ========================================= */

include("../database/peach_database.php");


/* =========================================
   PHPWORD
   ========================================= */

require_once("../vendor/autoload.php");

use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\IOFactory;


/* =========================================
   GET APPOINTMENT RECORDS
   ========================================= */

$result = mysqli_query(
    $connection,
    "SELECT
        appointment.appointment_id,
        patient.patient_name,
        doctor.doctor_name,
        appointment.appointment_date,
        appointment.appointment_time

     FROM appointment

     INNER JOIN patient
     ON appointment.patient_id = patient.patient_id

     INNER JOIN doctor
     ON appointment.doctor_id = doctor.doctor_id

     ORDER BY appointment.appointment_date DESC,
              appointment.appointment_time DESC"
);


if (!$result)
{
    die(
        "Unable to retrieve appointment records: "
        . mysqli_error($connection)
    );
}


/* =========================================
   CREATE WORD DOCUMENT
   ========================================= */

$phpWord = new PhpWord();

$section = $phpWord->addSection();


/* =========================================
   TITLE
   ========================================= */

$section->addText(
    "CAREFLOW",
    array(
        "bold" => true,
        "size" => 18
    ),
    array(
        "alignment" => "center"
    )
);


$section->addText(
    "Hospital Management System",
    array(
        "size" => 11
    ),
    array(
        "alignment" => "center"
    )
);


$section->addText(
    "Appointment Report",
    array(
        "bold" => true,
        "size" => 14
    ),
    array(
        "alignment" => "center",
        "spaceAfter" => 300
    )
);


/* =========================================
   CREATE TABLE
   ========================================= */

$table = $section->addTable(
    array(
        "borderSize" => 6,
        "borderColor" => "999999",
        "cellMargin" => 80
    )
);


/* =========================================
   TABLE HEADER
   ========================================= */

$table->addRow();


$table->addCell(1500)->addText(
    "Appointment ID",
    array("bold" => true)
);


$table->addCell(2500)->addText(
    "Patient",
    array("bold" => true)
);


$table->addCell(2500)->addText(
    "Doctor",
    array("bold" => true)
);


$table->addCell(2000)->addText(
    "Date",
    array("bold" => true)
);


$table->addCell(1800)->addText(
    "Time",
    array("bold" => true)
);


/* =========================================
   APPOINTMENT DATA
   ========================================= */

while ($row = mysqli_fetch_assoc($result))
{

    $table->addRow();


    $table->addCell(1500)->addText(
        $row["appointment_id"]
    );


    $table->addCell(2500)->addText(
        $row["patient_name"]
    );


    $table->addCell(2500)->addText(
        $row["doctor_name"]
    );


    $table->addCell(2000)->addText(
        $row["appointment_date"]
    );


    $table->addCell(1800)->addText(
        $row["appointment_time"]
    );

}


/* =========================================
   FOOTER
   ========================================= */

$section->addText(
    "Generated by CAREFLOW Hospital Management System",
    array(
        "size" => 9,
        "color" => "666666"
    ),
    array(
        "alignment" => "center",
        "spaceBefore" => 300
    )
);


/* =========================================
   DOWNLOAD DOCX
   ========================================= */

header(
    "Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document"
);

header(
    "Content-Disposition: attachment; filename=appointment_list.docx"
);

header(
    "Cache-Control: max-age=0"
);


$writer = IOFactory::createWriter(
    $phpWord,
    "Word2007"
);


$writer->save("php://output");

exit();

?>

