
<?php

session_start();


/* =========================================
   CHECK LOGIN
   ========================================= */

if (
    !isset($_SESSION["user_id"]) ||
    !isset($_SESSION["role"])
)
{
    header("Location: ../avocado_login.php");
    exit();
}


/* =========================================
   ROLE ACCESS
   ========================================= */

$allowed_roles = array(
    "System Administrator",
    "Doctor"
);


if (!in_array($_SESSION["role"], $allowed_roles))
{
    die("Access denied.");
}


/* =========================================
   DATABASE CONNECTION
   ========================================= */

include("../database/peach_database.php");


/* =========================================
   PHPWORD
   ========================================= */

require_once("../vendor/autoload.php");

use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\IOFactory;


/* =========================================
   GET DOCTOR RECORDS
   ========================================= */

$result = mysqli_query(
    $connection,
    "SELECT
        doctor_id,
        doctor_name,
        specialization,
        email,
        phone
     FROM doctor
     ORDER BY doctor_name"
);


if (!$result)
{
    die(
        "Unable to retrieve doctor records: "
        . mysqli_error($connection)
    );
}


/* =========================================
   CREATE WORD DOCUMENT
   ========================================= */

$phpWord = new PhpWord();


$section = $phpWord->addSection();


/* =========================================
   TITLE
   ========================================= */

$section->addText(
    "CAREFLOW",
    array(
        "bold" => true,
        "size" => 18
    ),
    array(
        "alignment" => "center"
    )
);


$section->addText(
    "Hospital Management System",
    array(
        "size" => 11
    ),
    array(
        "alignment" => "center"
    )
);


$section->addText(
    "Doctor Report",
    array(
        "bold" => true,
        "size" => 14
    ),
    array(
        "alignment" => "center",
        "spaceAfter" => 300
    )
);


/* =========================================
   CREATE TABLE
   ========================================= */

$table = $section->addTable(
    array(
        "borderSize" => 6,
        "borderColor" => "999999",
        "cellMargin" => 80
    )
);


/* =========================================
   TABLE HEADER
   ========================================= */

$table->addRow();


$table->addCell(1000)->addText(
    "Doctor ID",
    array("bold" => true)
);


$table->addCell(2500)->addText(
    "Doctor Name",
    array("bold" => true)
);


$table->addCell(2500)->addText(
    "Specialization",
    array("bold" => true)
);


$table->addCell(3000)->addText(
    "Email",
    array("bold" => true)
);


$table->addCell(1800)->addText(
    "Phone",
    array("bold" => true)
);


/* =========================================
   DOCTOR DATA
   ========================================= */

while ($row = mysqli_fetch_assoc($result))
{

    $table->addRow();


    $table->addCell(1000)->addText(
        $row["doctor_id"]
    );


    $table->addCell(2500)->addText(
        $row["doctor_name"]
    );


    $table->addCell(2500)->addText(
        $row["specialization"]
    );


    $table->addCell(3000)->addText(
        $row["email"]
    );


    $table->addCell(1800)->addText(
        $row["phone"]
    );

}


/* =========================================
   FOOTER
   ========================================= */

$section->addText(
    "Generated by CAREFLOW Hospital Management System",
    array(
        "size" => 9,
        "color" => "666666"
    ),
    array(
        "alignment" => "center",
        "spaceBefore" => 300
    )
);


/* =========================================
   SAVE AS DOCX DOWNLOAD
   ========================================= */

header(
    "Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document"
);

header(
    "Content-Disposition: attachment; filename=doctor_list.docx"
);

header(
    "Cache-Control: max-age=0"
);


$writer = IOFactory::createWriter(
    $phpWord,
    "Word2007"
);


$writer->save("php://output");

exit();

?>
