
<?php

session_start();


/* =========================================
   CHECK LOGIN
   ========================================= */

if (
    !isset($_SESSION["user_id"]) ||
    !isset($_SESSION["role"])
)
{
    header("Location: ../avocado_login.php");
    exit();
}


/* =========================================
   ROLE ACCESS
   ========================================= */

$allowed_roles = array(
    "System Administrator",
    "Doctor",
    "Nurse"
);


if (!in_array($_SESSION["role"], $allowed_roles))
{
    die("Access denied.");
}


/* =========================================
   DATABASE CONNECTION
   ========================================= */

include("../database/peach_database.php");


/* =========================================
   PHPWORD
   ========================================= */

require_once("../vendor/autoload.php");

use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\IOFactory;


/* =========================================
   GET MEDICAL RECORDS
   ========================================= */

$result = mysqli_query(
    $connection,

    "SELECT
        medical_record.record_id,
        patient.patient_name,
        medical_record.diagnosis,
        medical_record.treatment,
        medical_record.medicine

     FROM medical_record

     INNER JOIN patient
     ON medical_record.patient_id = patient.patient_id

     ORDER BY medical_record.record_id DESC"
);


if (!$result)
{
    die(
        "Unable to retrieve medical records: "
        . mysqli_error($connection)
    );
}


/* =========================================
   CREATE WORD DOCUMENT
   ========================================= */

$phpWord = new PhpWord();

$section = $phpWord->addSection();


/* =========================================
   TITLE
   ========================================= */

$section->addText(
    "CAREFLOW",
    array(
        "bold" => true,
        "size" => 18
    ),
    array(
        "alignment" => "center"
    )
);


$section->addText(
    "Hospital Management System",
    array(
        "size" => 11
    ),
    array(
        "alignment" => "center"
    )
);


$section->addText(
    "Medical Record Report",
    array(
        "bold" => true,
        "size" => 14
    ),
    array(
        "alignment" => "center",
        "spaceAfter" => 300
    )
);


/* =========================================
   CREATE TABLE
   ========================================= */

$table = $section->addTable(
    array(
        "borderSize" => 6,
        "borderColor" => "999999",
        "cellMargin" => 80
    )
);


/* =========================================
   TABLE HEADER
   ========================================= */

$table->addRow();


$table->addCell(1200)->addText(
    "Record ID",
    array("bold" => true)
);


$table->addCell(2200)->addText(
    "Patient",
    array("bold" => true)
);


$table->addCell(2500)->addText(
    "Diagnosis",
    array("bold" => true)
);


$table->addCell(2500)->addText(
    "Treatment",
    array("bold" => true)
);


$table->addCell(2500)->addText(
    "Medicine",
    array("bold" => true)
);


/* =========================================
   MEDICAL RECORD DATA
   ========================================= */

while ($row = mysqli_fetch_assoc($result))
{

    $table->addRow();


    $table->addCell(1200)->addText(
        $row["record_id"]
    );


    $table->addCell(2200)->addText(
        $row["patient_name"]
    );


    $table->addCell(2500)->addText(
        $row["diagnosis"]
    );


    $table->addCell(2500)->addText(
        $row["treatment"]
    );


    $table->addCell(2500)->addText(
        $row["medicine"]
    );

}


/* =========================================
   FOOTER
   ========================================= */

$section->addText(
    "Generated by CAREFLOW Hospital Management System",
    array(
        "size" => 9,
        "color" => "666666"
    ),
    array(
        "alignment" => "center",
        "spaceBefore" => 300
    )
);


/* =========================================
   DOWNLOAD DOCX
   ========================================= */

header(
    "Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document"
);

header(
    "Content-Disposition: attachment; filename=medical_record_list.docx"
);

header(
    "Cache-Control: max-age=0"
);


$writer = IOFactory::createWriter(
    $phpWord,
    "Word2007"
);


$writer->save("php://output");

exit();

?>
