
<?php

session_start();


/* =========================================
   CHECK LOGIN
   ========================================= */

if (
    !isset($_SESSION["user_id"]) ||
    !isset($_SESSION["role"])
)
{
    header("Location: ../avocado_login.php");
    exit();
}


/* =========================================
   ROLE ACCESS
   ========================================= */

$allowed_roles = array(
    "System Administrator",
    "Doctor",
    "Nurse"
);


if (!in_array($_SESSION["role"], $allowed_roles))
{
    die("Access denied.");
}


/* =========================================
   DATABASE CONNECTION
   ========================================= */

include("../database/peach_database.php");


/* =========================================
   DOMPDF
   ========================================= */

require_once("../vendor/autoload.php");

use Dompdf\Dompdf;
use Dompdf\Options;


/* =========================================
   GET MEDICAL RECORDS
   ========================================= */

$result = mysqli_query(
    $connection,

    "SELECT
        medical_record.record_id,
        patient.patient_name,
        medical_record.diagnosis,
        medical_record.treatment,
        medical_record.medicine

     FROM medical_record

     INNER JOIN patient
     ON medical_record.patient_id = patient.patient_id

     ORDER BY medical_record.record_id DESC"
);


if (!$result)
{
    die(
        "Unable to retrieve medical records: "
        . mysqli_error($connection)
    );
}


/* =========================================
   CREATE HTML
   ========================================= */

$html = '

<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<style>

body
{
    font-family: DejaVu Sans, sans-serif;
    font-size: 9px;
}

h1
{
    text-align:center;
    margin-bottom:5px;
}

.subtitle
{
    text-align:center;
    margin-bottom:20px;
    color:#555;
}

table
{
    width:100%;
    border-collapse:collapse;
}

th
{
    background:#eeeeee;
    border:1px solid #999;
    padding:7px;
    text-align:left;
}

td
{
    border:1px solid #cccccc;
    padding:6px;
    vertical-align:top;
}

.footer
{
    margin-top:20px;
    text-align:center;
    font-size:8px;
    color:#666;
}

</style>

</head>

<body>

<h1>CAREFLOW</h1>

<div class="subtitle">

Hospital Management System<br>

Medical Record Report

</div>

<table>

<thead>

<tr>

<th>Record ID</th>

<th>Patient</th>

<th>Diagnosis</th>

<th>Treatment</th>

<th>Medicine</th>

</tr>

</thead>

<tbody>

';


/* =========================================
   ADD MEDICAL RECORD DATA
   ========================================= */

while ($row = mysqli_fetch_assoc($result))
{

    $html .= '

    <tr>

    <td>' .
    htmlspecialchars($row["record_id"]) .
    '</td>

    <td>' .
    htmlspecialchars($row["patient_name"]) .
    '</td>

    <td>' .
    htmlspecialchars($row["diagnosis"]) .
    '</td>

    <td>' .
    htmlspecialchars($row["treatment"]) .
    '</td>

    <td>' .
    htmlspecialchars($row["medicine"]) .
    '</td>

    </tr>

    ';

}


$html .= '

</tbody>

</table>

<div class="footer">

Generated by CAREFLOW Hospital Management System

</div>

</body>

</html>

';


/* =========================================
   CREATE PDF
   ========================================= */

$options = new Options();

$options->set(
    "isRemoteEnabled",
    true
);


$dompdf = new Dompdf($options);


$dompdf->loadHtml($html);


$dompdf->setPaper(
    "A4",
    "landscape"
);


$dompdf->render();


/* =========================================
   DOWNLOAD PDF
   ========================================= */

$dompdf->stream(
    "medical_record_list.pdf",
    array(
        "Attachment" => true
    )
);

exit();

?>
