
<?php

/* =========================================
   START SESSION
   ========================================= */

session_start();


/* =========================================
   CHECK LOGIN
   ========================================= */

if (
    !isset($_SESSION["user_id"]) ||
    !isset($_SESSION["role"])
)
{
    header("Location: ../avocado_login.php");
    exit();
}


/* =========================================
   ROLE ACCESS
   ========================================= */

$allowed_roles = array(
    "System Administrator",
    "Doctor",
    "Nurse",
    "Reception"
);

if (!in_array($_SESSION["role"], $allowed_roles))
{
    die("Access denied.");
}


/* =========================================
   DATABASE CONNECTION
   ========================================= */

include("../database/peach_database.php");


/* =========================================
   DOMPDF
   ========================================= */

require_once("../vendor/autoload.php");

use Dompdf\Dompdf;
use Dompdf\Options;


/* =========================================
   GET PATIENT RECORDS
   ========================================= */

$result = mysqli_query(
    $connection,
    "SELECT
        patient_id,
        patient_name,
        gender,
        age,
        phone,
        address,
        registration_date
     FROM patient
     ORDER BY patient_name"
);


if (!$result)
{
    die(
        "Unable to retrieve patient records: "
        . mysqli_error($connection)
    );
}


/* =========================================
   CREATE HTML
   ========================================= */

$html = '

<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<style>

body
{
    font-family: DejaVu Sans, sans-serif;
    font-size: 10px;
}

h1
{
    text-align:center;
    margin-bottom:5px;
}

.subtitle
{
    text-align:center;
    margin-bottom:20px;
    color:#555;
}

table
{
    width:100%;
    border-collapse:collapse;
}

th
{
    background:#eeeeee;
    border:1px solid #999;
    padding:7px;
    text-align:left;
}

td
{
    border:1px solid #cccccc;
    padding:6px;
}

.footer
{
    margin-top:20px;
    text-align:center;
    font-size:9px;
    color:#666;
}

</style>

</head>

<body>

<h1>CAREFLOW</h1>

<div class="subtitle">
Hospital Management System<br>
Patient Report
</div>

<table>

<thead>

<tr>

<th>Patient ID</th>

<th>Patient Name</th>

<th>Gender</th>

<th>Age</th>

<th>Phone</th>

<th>Address</th>

<th>Registration Date</th>

</tr>

</thead>

<tbody>
';


/* =========================================
   ADD PATIENT DATA
   ========================================= */

while ($row = mysqli_fetch_assoc($result))
{

    $html .= '

    <tr>

    <td>' .
    htmlspecialchars($row["patient_id"]) .
    '</td>

    <td>' .
    htmlspecialchars($row["patient_name"]) .
    '</td>

    <td>' .
    htmlspecialchars($row["gender"]) .
    '</td>

    <td>' .
    htmlspecialchars($row["age"]) .
    '</td>

    <td>' .
    htmlspecialchars($row["phone"]) .
    '</td>

    <td>' .
    htmlspecialchars($row["address"]) .
    '</td>

    <td>' .
    htmlspecialchars($row["registration_date"]) .
    '</td>

    </tr>

    ';

}


$html .= '

</tbody>

</table>

<div class="footer">

Generated by CAREFLOW Hospital Management System

</div>

</body>

</html>
';


/* =========================================
   CREATE PDF
   ========================================= */

$options = new Options();

$options->set(
    "isRemoteEnabled",
    true
);

$dompdf = new Dompdf($options);

$dompdf->loadHtml($html);

$dompdf->setPaper(
    "A4",
    "landscape"
);

$dompdf->render();


/* =========================================
   DOWNLOAD PDF
   ========================================= */

$dompdf->stream(
    "patient_list.pdf",
    array(
        "Attachment" => true
    )
);

exit();

?>
