
<?php

/* =========================================
   START SESSION
   ========================================= */

session_start();


/* =========================================
   CHECK LOGIN
   ========================================= */

if (
    !isset($_SESSION["user_id"]) ||
    !isset($_SESSION["role"])
)
{
    header("Location: ../avocado_login.php");
    exit();
}


/* =========================================
   ROLE ACCESS
   ========================================= */

$allowed_roles = array(
    "System Administrator",
    "Doctor",
    "Nurse",
    "Reception"
);

if (!in_array($_SESSION["role"], $allowed_roles))
{
    die("Access denied.");
}


/* =========================================
   DATABASE CONNECTION
   ========================================= */

include("../database/peach_database.php");


/* =========================================
   PHPWORD
   ========================================= */

require_once("../vendor/autoload.php");

use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\IOFactory;


/* =========================================
   GET PATIENT RECORDS
   ========================================= */

$result = mysqli_query(
    $connection,
    "SELECT
        patient_id,
        patient_name,
        gender,
        age,
        phone,
        address,
        registration_date
     FROM patient
     ORDER BY patient_name"
);


if (!$result)
{
    die(
        "Unable to retrieve patient records: "
        . mysqli_error($connection)
    );
}


/* =========================================
   CREATE WORD DOCUMENT
   ========================================= */

$phpWord = new PhpWord();


$section = $phpWord->addSection();


/* =========================================
   TITLE
   ========================================= */

$section->addText(
    "CAREFLOW",
    array(
        "bold" => true,
        "size" => 20
    ),
    array(
        "alignment" => "center"
    )
);


$section->addText(
    "Hospital Management System",
    array(
        "size" => 12
    ),
    array(
        "alignment" => "center"
    )
);


$section->addText(
    "Patient Report",
    array(
        "bold" => true,
        "size" => 14
    ),
    array(
        "alignment" => "center"
    )
);


$section->addTextBreak(1);


/* =========================================
   CREATE TABLE
   ========================================= */

$table = $section->addTable(
    array(
        "borderSize" => 6,
        "borderColor" => "999999",
        "cellMargin" => 80
    )
);


/* =========================================
   TABLE HEADER
   ========================================= */

$table->addRow();

$table->addCell(900)->addText("ID");
$table->addCell(1800)->addText("Patient Name");
$table->addCell(1000)->addText("Gender");
$table->addCell(700)->addText("Age");
$table->addCell(1400)->addText("Phone");
$table->addCell(2500)->addText("Address");
$table->addCell(1600)->addText("Registration Date");


/* =========================================
   PATIENT DATA
   ========================================= */

while ($row = mysqli_fetch_assoc($result))
{

    $table->addRow();

    $table->addCell(900)
        ->addText($row["patient_id"]);

    $table->addCell(1800)
        ->addText($row["patient_name"]);

    $table->addCell(1000)
        ->addText($row["gender"]);

    $table->addCell(700)
        ->addText($row["age"]);

    $table->addCell(1400)
        ->addText($row["phone"]);

    $table->addCell(2500)
        ->addText($row["address"]);

    $table->addCell(1600)
        ->addText($row["registration_date"]);

}


/* =========================================
   FOOTER
   ========================================= */

$section->addTextBreak(1);

$section->addText(
    "Generated by CAREFLOW Hospital Management System",
    array(
        "italic" => true,
        "size" => 9
    ),
    array(
        "alignment" => "center"
    )
);


/* =========================================
   DOWNLOAD DOCX
   ========================================= */

header(
    "Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document"
);

header(
    "Content-Disposition: attachment; filename=patient_list.docx"
);

header(
    "Cache-Control: max-age=0"
);


$writer = IOFactory::createWriter(
    $phpWord,
    "Word2007"
);

$writer->save("php://output");

exit();

?>
